import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.scss";
import Link from "next/link";
import { ReactNode } from "react";
import { ShoppingCartProvider } from "@/features/cart/CartContext";
import ShoppingCartBtn from "@/components/ShoppingCartBtn";

const montserratAlternates = Montserrat_Alternates({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<ShoppingCartProvider>
			<html lang="en">
				<body className={`${montserratAlternates.className} flex min-h-screen flex-col gap-y-12`}>
					<nav className="sticky inset-x-0 top-0 h-20 bg-green-400">
						<div className="container mx-auto flex h-full items-center justify-between">
							<Link href="/" className="rounded-md bg-white px-3 py-1 font-extrabold text-green-400 shadow-2xl sm:px-6 sm:py-1.5 sm:text-2xl">
								My list
							</Link>
							<ShoppingCartBtn />
						</div>
					</nav>
					{children}
				</body>
			</html>
		</ShoppingCartProvider>
	);
}
